name: Build libmpv-android

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

env:
  NDK_VER: 27.0.12077973

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7
      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2.16.0
        with:
          channel: "stable"
      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v3.5.0
        with:
         gradle-version: 8.9
      - name: Cache
        uses: actions/cache@v4.0.2
        with:
          path: /usr/local/lib/android/sdk/ndk/${{ env.NDK_VER }}
          key: ${{ runner.os }}-${{ env.NDK_VER }}
      - name: Symlink SDK
        working-directory: ./buildscripts
        run: |
          mkdir sdk
          ln -s ${ANDROID_HOME} ./sdk/android-sdk-linux
      - name: Bundle (default)
        working-directory: ./buildscripts
        run: |
          sudo chmod +x bundle_default.sh
          ./bundle_default.sh
      - name: Bundle (full)
        working-directory: ./buildscripts
        run: |
          sudo chmod +x bundle_full.sh
          ./bundle_full.sh
      - name: Bundle (encoders-gpl)
        working-directory: ./buildscripts
        run: |
          sudo chmod +x bundle_encoders-gpl.sh
          ./bundle_encoders-gpl.sh
      - uses: actions/upload-artifact@v4.3.4
        with:
          name: artifact
          path: ./output/*
      - uses: softprops/action-gh-release@v2.0.8
        if: github.ref == 'refs/heads/main'
        with:
          draft: true
          prerelease: false
          tag_name: "vnext"
          files: |
            output/*
